import './globals.css'
import type { Metadata } from 'next'
import { Providers } from '@/src/redux/provider'
import { Inter, Silkscreen } from 'next/font/google'

const silkscreen = Silkscreen({ weight: '400', subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={silkscreen.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
